
image: php:8.1

pipelines:

  default:
    - step:
        script:
          - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libxml2-dev libxslt1-dev libicu-dev libc-client-dev libkrb5-dev libzip-dev zip

          - docker-php-ext-configure imap --with-kerberos --with-imap-ssl
          - docker-php-ext-configure gd --with-freetype --with-jpeg
          - docker-php-ext-install -j$(nproc) gd soap imap zip exif pcntl bcmath opcache

          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install

          - php artisan test

        caches:
          - composer
